In [105]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd 
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import pickle
from sklearn.externals import joblib 

In [106]:
import numpy as np
import pandas as pd

df=pd.read_csv("dataset.csv",encoding="latin1")
df

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                     -1              -1                           -1  ...   
1                      0               1                           -1  ...   
2                     -1              -1                           -1  ...   
3                     -1              -1                            1  ...   
4                      1               1                           -1  ...   
...                  ...             ...                          ...  ...   
11050                  1               1                           -1  ...   
11051                  1              -1                           -1  ...   
11052                  1              -1                           -1  ...   
11053                 -1              -1                            1  ...   
11054                 -1              -1                            1  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0                1       1             -1         -1           -1         -1   
1                1       1             -1         -1            0         -1   
2                1       1              1         -1            1         -1   
3                1       1             -1         -1            1         -1   
4               -1       1             -1         -1            0         -1   
...            ...     ...            ...        ...          ...        ...   
11050           -1      -1              1          1           -1         -1   
11051           -1       1              1          1            1          1   
11052            1       1              1          1            1         -1   
11053           -1       1              1          1            1         -1   
11054            1       1             -1          1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
0                 1                       1                  -1      -1  
1                 1                       1                   1      -1  
2                 1                       0                  -1      -1  
3                 1                      -1    

In [107]:
feature_names_df = ['having_IPhaving_IP_Address','URLURL_Length','having_At_Symbol','double_slash_redirecting','Prefix_Suffix','HTTPS_token','SFH','Submitting_to_email','Redirect','age_of_domain','Abnormal_URL','web_traffic']
x_df = df[feature_names_df]
y_df = df['Result']

In [108]:
x_df

having_IPhaving_IP_Address  URLURL_Length  having_At_Symbol  \
0                              -1              1                 1   
1                               1              1                 1   
2                               1              0                 1   
3                               1              0                 1   
4                               1              0                 1   
...                           ...            ...               ...   
11050                           1             -1                -1   
11051                          -1              1                -1   
11052                           1             -1                 1   
11053                          -1             -1                 1   
11054                          -1             -1                 1   

       double_slash_redirecting  Prefix_Suffix  HTTPS_token  SFH  \
0                            -1             -1           -1   -1   
1                             1             -1           -1   -1   
2                             1             -1           -1   -1   
3                             1             -1           -1   -1   
4                             1             -1            1   -1   
...                         ...            ...          ...  ...   
11050                         1              1            1   -1   
11051                        -1             -1            1    0   
11052                         1             -1            1   -1   
11053                         1             -1            1   -1   
11054                         1             -1            1   -1   

       Submitting_to_email  Redirect  age_of_domain  Abnormal_URL  web_traffic  
0                       -1         0             -1            -1           -1  
1                        1         0             -1             1            0  
2                       -1         0              1            -1            1  
3                        1         0             -1             1            1  
4                        1         0             -1             1            0  
...                    ...       ...            ...           ...          ...  
11050                   -1         0              1             1           -1  
11051                   -1         1              1            -1            1  
11052                    1         0              1             1            1  
11053                    1         0              1             1            1  
11054                    1         0             -1             1           -1  

[11055 rows x 12 columns]

In [109]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(x_df, y_df, random_state=0)

In [110]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=200,criterion='entropy')
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [111]:
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing

'''def multiclass_roc_auc_score(y_test, y_pred, average="macro"):
    lb = preprocessing.LabelBinarizer()
    lb.fit(y_test)
    y_test = lb.transform(y_test)
    y_pred = lb.transform(y_pred)
    return roc_auc_score(y_test, y_pred, average=average)'''

# Predict the transformed test documents
predictions = model.predict((X_test))

print('AUC: ', roc_auc_score(y_test, predictions))

AUC:  0.7964515506794875


In [112]:
print (X_test)

      having_IPhaving_IP_Address  URLURL_Length  having_At_Symbol  \
226                            1             -1                 1   
2252                           1             -1                 1   
2646                           1             -1                 1   
6444                           1             -1                 1   
1387                           1             -1                 1   
...                          ...            ...               ...   
6712                          -1             -1                 1   
3214                           1             -1                 1   
747                           -1             -1                 1   
5886                          -1             -1                 1   
2778                           1             -1                 1   

      double_slash_redirecting  Prefix_Suffix  HTTPS_token  SFH  \
226                          1             -1            1   -1   
2252                         1       

In [113]:
l=model.predict([[1,1,1,1,-1,1,1,-1,1,-1,1,-1]])
l

array([-1], dtype=int64)

In [114]:
l[0]

-1

In [115]:
filename = 'phish_trainedv3.sav'
pickle.dump(model, open(filename, 'wb'))

In [122]:
import whois
import datetime
text=input()
aburl=-1
digits="0123456789"
if text[8] in digits:
    oneval=-1
else:
    oneval=1    
if len(text)>170:
    secval=-1
else:
    secval=1  
if "@" in text:
    thirdval=-1
else:
    thirdval=1    
k=text.count("//")          
if k>1:
    fourthval=-1
else:
    fourthval=1  
if "-" in text:
    fifthval=-1
else:
    fifthval=1         
if "https" in text:
    sixthval=1
else:
    sixthval=-1
#subdomain ignored    

temp=text
temp=temp[6:]
k1=temp.count("https")

if k1 >=1:
    seventhval=-1
else:
    seventhval=1
if "about:blank" in text:
    eighthval=-1
else:
    eighthval=1
if "mail()" or "mailto:" in text:
    ninthval=-1
else:
    ninthval=1
re=text.count("//")          
if re>3:
    tenthval=-1
else:
    tenthval=1    

import whois
from datetime import datetime

url=text

try:
    res=whois.whois(url)
    print (res)
    #print (len(res['creation_date']))
    try:
        a=res['creation_date'][0]
        b=datetime.now()
        c=b-a
        d=c.days
    except:
        a=res['creation_date']
        b=datetime.now()
        c=b-a
        d=c.days
    #print (d)
    if d>365:
        eleventhval=1
    else:
        eleventhval=-1
except:
    aburl=1
    eleventhval=-1   

if aburl==1:
    twelthval=-1
else:
    twelthval=1    
    
import urllib.request, sys, re
import xmltodict, json

try:
    xml = urllib.request.urlopen('http://data.alexa.com/data?cli=10&dat=s&url={}'.format(text)).read()

    result= xmltodict.parse(xml)

    data = json.dumps(result).replace("@","")
    data_tojson = json.loads(data)
    url = data_tojson["ALEXA"]["SD"][1]["POPULARITY"]["URL"]
    rank= int(data_tojson["ALEXA"]["SD"][1]["POPULARITY"]["TEXT"])
    print (rank)
    if rank<=100000:
        thirt=1
    else:
        thirt=-1
    print (thirt)    
except:
    thirt=-1
    print (thirt)
    
print("site {site}, rank {rank}".format(site=url,rank=rank))    


print (oneval) #having ip   
print (secval) #length
print (thirdval) #atvalue
print (fourthval) #double slash
print (fifthval) #prefix suffix
#print (sixthval) #ssl
print (seventhval) #https token
print (eighthval) #sfh
print (ninthval) #submit to mail
print (tenthval) #redirect
print (eleventhval) #age of domain
print (twelthval) #abnormal url
print (thirt)

http://my3service.co.uk
-1
site http://my3service.co.uk, rank 5257061
1
1
1
1
1
1
1
-1
1
-1
-1
-1


In [123]:
model.predict([[oneval,secval,thirdval,fourthval,fifthval,seventhval,eighthval,ninthval,tenthval,eleventhval,twelthval,thirt]])

array([1], dtype=int64)

In [ ]:
import whois
import datetime
text=input()
aburl=-1
digits="0123456789"
if text[8] in digits:
    oneval=-1
else:
    oneval=1    
if len(text)>170:
    secval=-1
else:
    secval=1  
if "@" in text:
    thirdval=-1
else:
    thirdval=1    
k=text.count("//")          
if k>1:
    fourthval=-1
else:
    fourthval=1  
if "-" in text:
    fifthval=-1
else:
    fifthval=1         
if "https" in text:
    sixthval=1
else:
    sixthval=-1
#subdomain ignored    

temp=text
temp=temp[6:]
k1=temp.count("https")

if k1 >=1:
    seventhval=-1
else:
    seventhval=1
if "about:blank" in text:
    eighthval=-1
else:
    eighthval=1
if "mail()" or "mailto:" in text:
    ninthval=-1
else:
    ninthval=1
re=text.count("//")          
if re>3:
    tenthval=-1
else:
    tenthval=1    

import whois
from datetime import datetime

url=text

try:
    res=whois.whois(url)
    print (res)
    #print (len(res['creation_date']))
    try:
        a=res['creation_date'][0]
        b=datetime.now()
        c=b-a
        d=c.days
    except:
        a=res['creation_date']
        b=datetime.now()
        c=b-a
        d=c.days
    #print (d)
    if d>365:
        eleventhval=1
    else:
        eleventhval=-1
except:
    aburl=1
    eleventhval=-1   

if aburl==1:
    twelthval=-1
else:
    twelthval=1    


print (oneval) #having ip   
print (secval) #length
print (thirdval) #atvalue
print (fourthval) #double slash
print (fifthval) #prefix suffix
print (sixthval) #ssl
print (seventhval) #https token
print (eighthval) #sfh
print (ninthval) #submit to mail
print (tenthval) #redirect
print (eleventhval) #age of domain
print (twelthval) #abnormal url

In [50]:
model.predict([[oneval,secval,thirdval,fourthval,fifthval,sixthval,seventhval,eighthval,ninthval,tenthval,eleventhval,twelthval]])

array([1], dtype=int64)

In [53]:
import whois
import datetime
text=input()
aburl=-1
digits="0123456789"
if text[8] in digits:
    oneval=-1
else:
    oneval=1    
if len(text)>170:
    secval=-1
else:
    secval=1  
if "@" in text:
    thirdval=-1
else:
    thirdval=1    
k=text.count("//")          
if k>1:
    fourthval=-1
else:
    fourthval=1  
if "-" in text:
    fifthval=-1
else:
    fifthval=1         
if "https" in text:
    sixthval=1
else:
    sixthval=-1
#subdomain ignored    

temp=text
temp=temp[6:]
k1=temp.count("https")

if k1 >=1:
    seventhval=-1
else:
    seventhval=1
if "about:blank" in text:
    eighthval=-1
else:
    eighthval=1
if "mail()" or "mailto:" in text:
    ninthval=-1
else:
    ninthval=1
re=text.count("//")          
if re>3:
    tenthval=-1
else:
    tenthval=1    

import whois
from datetime import datetime

url=text

try:
    res=whois.whois(url)
    print (res)
    #print (len(res['creation_date']))
    try:
        a=res['creation_date'][0]
        b=datetime.now()
        c=b-a
        d=c.days
    except:
        a=res['creation_date']
        b=datetime.now()
        c=b-a
        d=c.days
    #print (d)
    if d>365:
        eleventhval=1
    else:
        eleventhval=-1
except:
    aburl=1
    eleventhval=-1   

if aburl==1:
    twelthval=-1
else:
    twelthval=1    


print (oneval) #having ip   
print (secval) #length
print (thirdval) #atvalue
print (fourthval) #double slash
print (fifthval) #prefix suffix
print (sixthval) #ssl
print (seventhval) #https token
print (eighthval) #sfh
print (ninthval) #submit to mail
print (tenthval) #redirect
print (eleventhval) #age of domain
print (twelthval) #abnormal url

http://www.confirme-paypal.com/
1
1
1
1
-1
-1
1
1
-1
1
-1
-1


In [54]:
model.predict([[oneval,secval,thirdval,fourthval,fifthval,sixthval,seventhval,eighthval,ninthval,tenthval,eleventhval,twelthval]])

array([-1], dtype=int64)

In [ ]:
#https://security.berkeley.edu/education-awareness/phishing/phishing-examples-archive

In [61]:
import whois
import datetime
text=input()
aburl=-1
digits="0123456789"
if text[8] in digits:
    oneval=-1
else:
    oneval=1    
if len(text)>170:
    secval=-1
else:
    secval=1  
if "@" in text:
    thirdval=-1
else:
    thirdval=1    
k=text.count("//")          
if k>1:
    fourthval=-1
else:
    fourthval=1  
if "-" in text:
    fifthval=-1
else:
    fifthval=1         
if "https" in text:
    sixthval=1
else:
    sixthval=-1
#subdomain ignored    

temp=text
temp=temp[6:]
k1=temp.count("https")

if k1 >=1:
    seventhval=-1
else:
    seventhval=1
if "about:blank" in text:
    eighthval=-1
else:
    eighthval=1
if "mail()" or "mailto:" in text:
    ninthval=-1
else:
    ninthval=1
re=text.count("//")          
if re>3:
    tenthval=-1
else:
    tenthval=1    

import whois
from datetime import datetime

url=text

try:
    res=whois.whois(url)
    print (res)
    #print (len(res['creation_date']))
    try:
        a=res['creation_date'][0]
        b=datetime.now()
        c=b-a
        d=c.days
    except:
        a=res['creation_date']
        b=datetime.now()
        c=b-a
        d=c.days
    #print (d)
    if d>365:
        eleventhval=1
    else:
        eleventhval=-1
except:
    aburl=1
    eleventhval=-1   

if aburl==1:
    twelthval=-1
else:
    twelthval=1    


print (oneval) #having ip   
print (secval) #length
print (thirdval) #atvalue
print (fourthval) #double slash
print (fifthval) #prefix suffix
print (sixthval) #ssl
print (seventhval) #https token
print (eighthval) #sfh
print (ninthval) #submit to mail
print (tenthval) #redirect
print (eleventhval) #age of domain
print (twelthval) #abnormal url

https://security.berk/education-awareness//phishing//phishing-examples-archive
{
  "domain_name": null,
  "registrar": null,
  "whois_server": null,
  "referral_url": null,
  "updated_date": null,
  "creation_date": null,
  "expiration_date": null,
  "name_servers": null,
  "status": null,
  "emails": null,
  "dnssec": null,
  "name": null,
  "org": null,
  "address": null,
  "city": null,
  "state": null,
  "zipcode": null,
  "country": null
}
1
1
1
-1
-1
1
1
1
-1
1
-1
-1


In [63]:
model.predict([[oneval,secval,thirdval,fourthval,fifthval,sixthval,seventhval,eighthval,ninthval,tenthval,eleventhval,twelthval]])

array([1], dtype=int64)

In [64]:
filename = 'phish_trainedv0.sav'
pickle.dump(model, open(filename, 'wb'))

In [69]:
loaded_model = joblib.load(filename)

arg=loaded_model.predict(([[oneval,secval,thirdval,fourthval,fifthval,sixthval,seventhval,eighthval,ninthval,tenthval,eleventhval,twelthval]]))
arg[0]


1

In [71]:
from json.encoder import JSONEncoder
final_entity = { "predicted_argument": [int(arg[0])]}
# directly called encode method of JSON
print (JSONEncoder().encode(final_entity))

{"predicted_argument": [1]}
